# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"
    # Group minor and patch updates
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      sentry:
        patterns:
          - "@sentry/*"
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Web frontend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(web)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "next"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Mobile dependencies
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "mobile"
    commit-message:
      prefix: "chore(mobile)"
      include: "scope"
    groups:
      react-native:
        patterns:
          - "react-native*"
          - "expo*"
          - "@expo/*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "monorepo"
    commit-message:
      prefix: "chore(root)"
      include: "scope"

  # Shared packages
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "shared"
    commit-message:
      prefix: "chore(shared)"
      include: "scope"

  # UI package
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "ui"
    commit-message:
      prefix: "chore(ui)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "joachimaross"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
