# Netlify Configuration for Quemiai
# This configuration file sets up the deployment for the Next.js frontend
# and configures serverless functions for the backend API

[build]
  # Base directory for the build
  base = "apps/web"
  
  # Build command - uses pnpm from root to build the web app
  command = "cd ../.. && pnpm install && pnpm --filter @quemiai/web build"
  
  # Publish directory - Next.js static export or standalone build
  publish = ".next"
  
  # Functions directory for serverless backend functions
  functions = "../../netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18.17.0"
  
  # Use pnpm
  NPM_FLAGS = "--version"
  PNPM_FLAGS = "--version"
  
  # Next.js build optimizations
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# Enable Next.js Runtime for Netlify
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugin configuration for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["visitor"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "0"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=60, s-maxage=31536000"

# Edge Functions configuration (optional, for advanced use cases)
[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"
  
  # Node bundler
  node_bundler = "esbuild"
  
  # External node modules to include
  external_node_modules = ["@prisma/client", "prisma"]
  
  # Function timeout (max 26 seconds for free tier, 900 for paid)
  [functions.timeouts]
    default = 26

# Development settings
[dev]
  command = "pnpm --filter @quemiai/web dev"
  port = 3000
  targetPort = 3000
  publish = "apps/web/.next"
  autoLaunch = true

# Context-specific configurations
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
