"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var users_1 = require("./users");
var posts_1 = require("./posts");
var messages_1 = require("./messages");
var analytics_1 = require("./analytics");
var marketplace_1 = require("./marketplace");
var ai_1 = require("./ai");
var auth_1 = require("./auth");
var router = (0, express_1.Router)();
router.use('/users', users_1.default);
router.use('/posts', posts_1.default);
router.use('/messages', messages_1.default);
router.use('/analytics', analytics_1.default);
router.use('/marketplace', marketplace_1.default);
router.use('/ai', ai_1.default);
router.use('/auth', auth_1.default);
exports.default = router;
