// Placeholder data for Quemi Social

import { User, Post, Story, StoryHighlight, Message, Conversation, Notification, UserSettings, Comment } from './types';

// Sample Users
export const currentUser: User = {
  id: '1',
  username: 'johndoe',
  displayName: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  coverPhoto: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=1200&h=400&fit=crop',
  bio: 'Full-stack developer | Coffee enthusiast ☕ | Building amazing things',
  location: 'San Francisco, CA',
  website: 'https://johndoe.dev',
  joinedAt: new Date('2023-01-15'),
  followersCount: 1250,
  followingCount: 380,
  isOnline: true,
};

export const users: User[] = [
  currentUser,
  {
    id: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    email: 'jane@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    coverPhoto: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&h=400&fit=crop',
    bio: 'Designer | Traveler 🌍 | Making the world beautiful',
    location: 'New York, NY',
    website: 'https://janedoe.design',
    joinedAt: new Date('2023-02-20'),
    followersCount: 890,
    followingCount: 420,
    isFollowing: true,
    isMutualFollow: true,
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: '3',
    username: 'mikejohnson',
    displayName: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    bio: 'Tech enthusiast | Gamer 🎮 | Always learning',
    location: 'Austin, TX',
    joinedAt: new Date('2023-03-10'),
    followersCount: 540,
    followingCount: 290,
    isFollowing: false,
    isOnline: false,
    lastSeen: new Date(Date.now() - 3600000),
  },
  {
    id: '4',
    username: 'sarahsmith',
    displayName: 'Sarah Smith',
    email: 'sarah@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Product Manager | Dog lover 🐕 | Startup life',
    location: 'Seattle, WA',
    joinedAt: new Date('2023-04-05'),
    followersCount: 2100,
    followingCount: 650,
    isFollowing: true,
    isMutualFollow: false,
    isOnline: true,
  },
  {
    id: '5',
    username: 'alexchen',
    displayName: 'Alex Chen',
    email: 'alex@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'AI/ML Engineer | Open source contributor',
    location: 'Boston, MA',
    joinedAt: new Date('2023-05-12'),
    followersCount: 1680,
    followingCount: 440,
    isFollowing: false,
    isOnline: false,
    lastSeen: new Date(Date.now() - 7200000),
  },
];

// Sample Posts
export const posts: Post[] = [
  {
    id: '1',
    userId: '2',
    user: users[1],
    content: 'Just launched my new portfolio website! Check it out and let me know what you think 🚀✨',
    media: [
      {
        id: 'm1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
        caption: 'Portfolio homepage',
      },
    ],
    type: 'post',
    likes: 245,
    comments: 38,
    shares: 12,
    isLiked: true,
    isBookmarked: false,
    tags: ['webdev', 'portfolio', 'design'],
    privacy: 'public',
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: '2',
    userId: '4',
    user: users[3],
    content: 'Excited to announce that our team just shipped v2.0! Amazing work everyone! 🎉',
    type: 'post',
    likes: 189,
    comments: 24,
    shares: 8,
    isLiked: false,
    isBookmarked: true,
    tags: ['startup', 'launch'],
    privacy: 'public',
    createdAt: new Date(Date.now() - 10800000),
  },
  {
    id: '3',
    userId: '3',
    user: users[2],
    content: 'Beautiful sunset from my hike today. Nature never disappoints! 🌄',
    media: [
      {
        id: 'm2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
      },
    ],
    type: 'post',
    likes: 412,
    comments: 56,
    shares: 23,
    isLiked: true,
    tags: ['nature', 'hiking'],
    privacy: 'public',
    createdAt: new Date(Date.now() - 14400000),
  },
  {
    id: '4',
    userId: '5',
    user: users[4],
    content: 'Working on an exciting new ML project. Stay tuned for updates! 🤖',
    type: 'post',
    likes: 98,
    comments: 15,
    shares: 5,
    isLiked: false,
    tags: ['AI', 'MachineLearning'],
    privacy: 'public',
    createdAt: new Date(Date.now() - 21600000),
  },
  {
    id: '5',
    userId: '1',
    user: users[0],
    content: 'Coffee and code - the perfect combo for a productive day! ☕💻',
    media: [
      {
        id: 'm3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop',
      },
    ],
    type: 'post',
    likes: 156,
    comments: 21,
    shares: 7,
    isPinned: true,
    tags: ['coding', 'coffee'],
    privacy: 'public',
    createdAt: new Date(Date.now() - 28800000),
  },
];

// Sample Comments
export const comments: Comment[] = [
  {
    id: 'c1',
    postId: '1',
    userId: '1',
    user: users[0],
    content: 'Looks amazing! Love the clean design 😍',
    likes: 12,
    replies: [],
    isLiked: false,
    createdAt: new Date(Date.now() - 7000000),
  },
  {
    id: 'c2',
    postId: '1',
    userId: '3',
    user: users[2],
    content: 'Great work! The animations are smooth 👏',
    likes: 8,
    replies: [],
    isLiked: true,
    createdAt: new Date(Date.now() - 6900000),
  },
  {
    id: 'c3',
    postId: '3',
    userId: '2',
    user: users[1],
    content: 'Stunning view! Which trail is this?',
    likes: 5,
    replies: [
      {
        id: 'c3-r1',
        postId: '3',
        userId: '3',
        user: users[2],
        content: 'This was the Mountain Peak Trail, highly recommend it!',
        likes: 3,
        replies: [],
        parentId: 'c3',
        createdAt: new Date(Date.now() - 14200000),
      },
    ],
    createdAt: new Date(Date.now() - 14300000),
  },
];

// Sample Stories
export const stories: Story[] = [
  {
    id: 's1',
    userId: '2',
    user: users[1],
    media: {
      id: 'sm1',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=700&fit=crop',
    },
    caption: 'Working from my favorite coffee shop ☕',
    views: 234,
    hasViewed: true,
    expiresAt: new Date(Date.now() + 43200000),
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 's2',
    userId: '4',
    user: users[3],
    media: {
      id: 'sm2',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=700&fit=crop',
    },
    caption: 'Coding late night 🌙',
    views: 156,
    hasViewed: false,
    expiresAt: new Date(Date.now() + 39600000),
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: 's3',
    userId: '3',
    user: users[2],
    media: {
      id: 'sm3',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=700&fit=crop',
    },
    caption: 'Beach day! 🏖️',
    views: 389,
    hasViewed: false,
    expiresAt: new Date(Date.now() + 36000000),
    createdAt: new Date(Date.now() - 10800000),
  },
];

// Sample Conversations and Messages
export const conversations: Conversation[] = [
  {
    id: 'conv1',
    type: 'direct',
    participants: [users[0], users[1]],
    lastMessage: {
      id: 'msg1',
      conversationId: 'conv1',
      senderId: '2',
      sender: users[1],
      content: 'Hey! Did you see my new portfolio? 😊',
      type: 'text',
      isRead: true,
      createdAt: new Date(Date.now() - 3600000),
    },
    unreadCount: 0,
    isPinned: true,
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'conv2',
    type: 'direct',
    participants: [users[0], users[3]],
    lastMessage: {
      id: 'msg2',
      conversationId: 'conv2',
      senderId: '4',
      sender: users[3],
      content: 'Great! Let\'s catch up tomorrow.',
      type: 'text',
      isRead: false,
      createdAt: new Date(Date.now() - 1800000),
    },
    unreadCount: 2,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date(Date.now() - 1800000),
  },
  {
    id: 'conv3',
    type: 'group',
    participants: [users[0], users[1], users[2], users[3]],
    name: 'Dev Team 🚀',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=DevTeam',
    lastMessage: {
      id: 'msg3',
      conversationId: 'conv3',
      senderId: '3',
      sender: users[2],
      content: 'Who\'s joining the standup?',
      type: 'text',
      isRead: true,
      createdAt: new Date(Date.now() - 7200000),
    },
    unreadCount: 0,
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date(Date.now() - 7200000),
  },
];

export const messages: Message[] = [
  {
    id: 'msg1',
    conversationId: 'conv1',
    senderId: '2',
    sender: users[1],
    content: 'Hey! Did you see my new portfolio? 😊',
    type: 'text',
    isRead: true,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'msg1-reply',
    conversationId: 'conv1',
    senderId: '1',
    sender: users[0],
    content: 'Yes! It looks fantastic! 🔥',
    type: 'text',
    isRead: true,
    createdAt: new Date(Date.now() - 3500000),
  },
  {
    id: 'msg2',
    conversationId: 'conv2',
    senderId: '1',
    sender: users[0],
    content: 'Hey Sarah, are you free for lunch this week?',
    type: 'text',
    isRead: true,
    createdAt: new Date(Date.now() - 2000000),
  },
  {
    id: 'msg2-reply',
    conversationId: 'conv2',
    senderId: '4',
    sender: users[3],
    content: 'Great! Let\'s catch up tomorrow.',
    type: 'text',
    isRead: false,
    createdAt: new Date(Date.now() - 1800000),
  },
];

// Sample Notifications
export const notifications: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    fromUser: users[1],
    post: posts[4],
    content: 'liked your post',
    isRead: false,
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    id: 'n2',
    type: 'comment',
    fromUser: users[2],
    post: posts[0],
    content: 'commented on your post',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'n3',
    type: 'follow',
    fromUser: users[4],
    content: 'started following you',
    isRead: true,
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: 'n4',
    type: 'mention',
    fromUser: users[3],
    post: posts[1],
    content: 'mentioned you in a post',
    isRead: true,
    createdAt: new Date(Date.now() - 10800000),
  },
  {
    id: 'n5',
    type: 'message',
    fromUser: users[1],
    message: messages[0],
    content: 'sent you a message',
    isRead: true,
    createdAt: new Date(Date.now() - 14400000),
  },
];

// Sample User Settings
export const userSettings: UserSettings = {
  userId: '1',
  theme: 'dark',
  notificationsEnabled: true,
  emailNotifications: true,
  pushNotifications: true,
  messageNotifications: true,
  accountPrivacy: 'public',
  showOnlineStatus: true,
  allowTagging: true,
  allowComments: true,
  blockedUsers: [],
  mutedUsers: [],
  chatBubbleColor: '#0066FF',
  fontSize: 'medium',
};
