name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Security Audit (Block High/Critical)
        run: |
          echo "🔒 Running security audit..."
          pnpm audit --audit-level=high || {
            echo "❌ High or Critical vulnerabilities found!"
            echo "Please run 'pnpm audit --fix' to resolve vulnerabilities"
            exit 1
          }

      - name: Run Linter
        run: pnpm run lint
        continue-on-error: true

      - name: Run Tests
        run: pnpm run test

      - name: Run Test Coverage
        run: pnpm run test:cov

      - name: Check Test Coverage Threshold
        run: |
          echo "📊 Checking test coverage..."
          # Extract coverage percentage (this is a simple check, adjust as needed)
          # For now, we'll just report it without failing
          echo "Coverage check completed"
        continue-on-error: true

      - name: Build Project
        run: pnpm run build

      - name: Upload coverage to Codecov (optional)
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          directory: ./coverage
          fail_ci_if_error: false

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for secret scanning

      - name: Run Trufflehog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --debug --only-verified
