name: Snyk Security Scan

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    # Run weekly on Tuesday at 9 AM UTC
    - cron: '0 9 * * 2'
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: backend
            path: apps/backend
          - name: web
            path: apps/web
          - name: mobile
            path: apps/mobile
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ${{ matrix.target.path }}
        run: npm ci --ignore-scripts || npm install --ignore-scripts

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=${{ matrix.target.path }}/package.json
          command: test

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk.sarif

  snyk-monitor:
    name: Snyk Continuous Monitoring
    runs-on: ubuntu-latest
    # Only run on main branch to avoid duplicate monitoring
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        working-directory: apps/backend
        run: npm ci --ignore-scripts || npm install --ignore-scripts

      - name: Snyk Monitor Backend
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=apps/backend/package.json --project-name=quemiai-backend
